import { ZodiacInfo } from "./types";

export const ZODIAC_SIGNS: ZodiacInfo[] = [
  {
    id: "Aries",
    hindiName: "मेष",
    dateRange: "Mar 21 - Apr 19",
    element: "Fire",
    rulingPlanet: "Mars",
    symbol: "♈",
  },
  {
    id: "Taurus",
    hindiName: "वृषभ",
    dateRange: "Apr 20 - May 20",
    element: "Earth",
    rulingPlanet: "Venus",
    symbol: "♉",
  },
  {
    id: "Gemini",
    hindiName: "मिथुन",
    dateRange: "May 21 - Jun 20",
    element: "Air",
    rulingPlanet: "Mercury",
    symbol: "♊",
  },
  {
    id: "Cancer",
    hindiName: "कर्क",
    dateRange: "Jun 21 - Jul 22",
    element: "Water",
    rulingPlanet: "Moon",
    symbol: "♋",
  },
  {
    id: "Leo",
    hindiName: "सिंह",
    dateRange: "Jul 23 - Aug 22",
    element: "Fire",
    rulingPlanet: "Sun",
    symbol: "♌",
  },
  {
    id: "Virgo",
    hindiName: "कन्या",
    dateRange: "Aug 23 - Sep 22",
    element: "Earth",
    rulingPlanet: "Mercury",
    symbol: "♍",
  },
  {
    id: "Libra",
    hindiName: "तुला",
    dateRange: "Sep 23 - Oct 22",
    element: "Air",
    rulingPlanet: "Venus",
    symbol: "♎",
  },
  {
    id: "Scorpio",
    hindiName: "वृश्चिक",
    dateRange: "Oct 23 - Nov 21",
    element: "Water",
    rulingPlanet: "Pluto",
    symbol: "♏",
  },
  {
    id: "Sagittarius",
    hindiName: "धनु",
    dateRange: "Nov 22 - Dec 21",
    element: "Fire",
    rulingPlanet: "Jupiter",
    symbol: "♐",
  },
  {
    id: "Capricorn",
    hindiName: "मकर",
    dateRange: "Dec 22 - Jan 19",
    element: "Earth",
    rulingPlanet: "Saturn",
    symbol: "♑",
  },
  {
    id: "Aquarius",
    hindiName: "कुंभ",
    dateRange: "Jan 20 - Feb 18",
    element: "Air",
    rulingPlanet: "Uranus",
    symbol: "♒",
  },
  {
    id: "Pisces",
    hindiName: "मीन",
    dateRange: "Feb 19 - Mar 20",
    element: "Water",
    rulingPlanet: "Neptune",
    symbol: "♓",
  },
];
